#ifndef CONFIG_H
#define CONFIG_H

#define ENABLE 1

#define DARK_THRESHOLD 0.2
#define CARPET_THRESHOLD 125
#define STEERING_MULTIPLIER .0035
#define STEERING_START 0.4

#define REQUIRED_DIFF 1

#define DEFAULT_KP 0.00675
#define DEFAULT_KI 0.0125
#define DEFAULT_KD -.2 

#define MOTOR_CONST 1.5

#define STEERING_SPEED_MULTIPLIER 0.5

#define MODE_AGGRESSIVE 0
#define MODE_PASSIVE_AGGRESSIVE 1
#define MODE_PASSIVE 2

// #define AGGRESSIVE_SPEED 80
// #define PASSIVE_AGGRESSIVE_SPEED 70
// #define PASSIVE_SPEED 60

#define AGGRESSIVE_SPEED 70
#define PASSIVE_AGGRESSIVE_SPEED 60
#define PASSIVE_SPEED 45

#endif